'use client';
import CardTile from './CardTile';
import ManaCurve from './ManaCurve';
import { DeckViewMode, EdhCard, EdhDeckCardEntry, EdhDeckLayout } from '@/lib/edh/types';
import { primaryCardType, TYPE_LABEL_ZH, TYPE_ORDER } from '@/lib/edh/mana';

export default function DeckBoard({ entries, commanderOracleId, cardOf, layout, onDropCard, onMoveCard, onRemoveOne, onSetCommander, onClearCommander, onDetails }: { entries: EdhDeckCardEntry[]; commanderOracleId: string|null; cardOf:(id:string)=>EdhCard|undefined; layout:EdhDeckLayout; onDropCard:(id:string, point?:{x:number;y:number})=>void; onMoveCard:(id:string, point:{x:number;y:number})=>void; onRemoveOne:(card:EdhCard)=>void; onSetCommander:(card:EdhCard)=>void; onClearCommander:()=>void; onDetails:(card:EdhCard)=>void }) {
 const commander=commanderOracleId?cardOf(commanderOracleId):undefined; const total=entries.reduce((s,e)=>s+e.quantity,0)+(commander?1:0);
 const drop=(e:React.DragEvent, commanderSlot=false)=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-edh-oracle-id');if(!id)return;const card=cardOf(id);if(commanderSlot&&card){onSetCommander(card);return;}if(e.dataTransfer.getData('application/x-edh-existing')) return;const r=e.currentTarget.getBoundingClientRect();onDropCard(id,{x:e.clientX-r.left,y:e.clientY-r.top});};
 const cards=entries.map(e=>({entry:e,card:cardOf(e.oracleId)})).filter((x):x is {entry:EdhDeckCardEntry;card:EdhCard}=>Boolean(x.card));
 const grouped=new Map<string,typeof cards>(); TYPE_ORDER.forEach(t=>grouped.set(t,[])); cards.forEach(x=>grouped.get(primaryCardType(x.card.typeLine))?.push(x));
 const renderTile=(entry:EdhDeckCardEntry,card:EdhCard, style?:React.CSSProperties)=><div key={entry.oracleId} style={style} draggable onDragStart={(e)=>{e.dataTransfer.setData('application/x-edh-oracle-id',entry.oracleId);e.dataTransfer.setData('application/x-edh-existing','1');}}><CardTile card={card} quantity={entry.quantity} onRemove={onRemoveOne} onDetails={onDetails} draggable={false}/></div>;
 const sort=(mode:DeckViewMode)=> mode==='cmc'?[...cards].sort((a,b)=>a.card.cmc-b.card.cmc):mode==='type'?[...cards].sort((a,b)=>primaryCardType(a.card.typeLine).localeCompare(primaryCardType(b.card.typeLine))):cards;
 return <div className="flex h-full flex-col"><div className="flex justify-between border-b border-white/10 pb-3"><b>牌组桌面</b><span className={total===100?'text-emerald-300':'text-amber-300'}>{total}/100</span></div>
 <div onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,true)} className="mt-3 flex min-h-36 items-center gap-4 rounded-2xl border-2 border-dashed border-amber-300/30 bg-amber-300/[.04] p-3"><div className="text-xs text-amber-200">指挥官槽位<br/><span className="text-slate-500">拖入可作指挥官的牌</span></div>{commander?<div className="w-24"><CardTile card={commander} isCommander onDetails={onDetails} draggable={false}/><button onClick={onClearCommander} className="mt-1 text-xs text-rose-300">移除指挥官</button></div>:<div className="text-sm text-slate-500">空</div>}</div>
 <div className="mt-3 rounded-xl border border-white/10 bg-white/[.02] p-3"><ManaCurve entries={entries} cardOf={cardOf}/></div>
 <div onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e)} className="relative mt-3 min-h-[360px] flex-1 overflow-auto rounded-2xl border border-white/10 bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,.08),transparent_60%)] p-4 sm:min-h-[500px]">
 {cards.length===0?<p className="grid h-full place-items-center text-slate-500">拖拽搜索结果到桌面，或在卡牌详情中加入牌组</p>:layout.viewMode==='free'?<div className="relative min-h-[420px] sm:min-h-[620px]">{cards.map(({entry,card},i)=>{const p=layout.positions[entry.oracleId]||{x:(i%5)*105,y:Math.floor(i/5)*170};return <div key={entry.oracleId} className="absolute w-24" style={{left:p.x,top:p.y}} onDragEnd={e=>{const r=e.currentTarget.parentElement!.getBoundingClientRect();onMoveCard(entry.oracleId,{x:e.clientX-r.left,y:e.clientY-r.top});}}>{renderTile(entry,card)}</div>;})}</div>:<div className="space-y-5">{layout.viewMode==='type'?TYPE_ORDER.map(t=>{const g=grouped.get(t)||[];return g.length?<section key={t}><p className="mb-2 text-xs text-slate-500">{TYPE_LABEL_ZH[t]}</p><div className="grid grid-cols-[repeat(auto-fill,minmax(84px,1fr))] gap-3">{g.map(x=>renderTile(x.entry,x.card))}</div></section>:null;}):Array.from({length:8},(_,cmc)=>{const g=sort('cmc').filter(x=>Math.min(Math.round(x.card.cmc),7)===cmc);return g.length?<section key={cmc}><p className="mb-2 text-xs text-slate-500">法术力 {cmc===7?'7+':cmc}</p><div className="grid grid-cols-[repeat(auto-fill,minmax(84px,1fr))] gap-3">{g.map(x=>renderTile(x.entry,x.card))}</div></section>:null;})}</div>}
 </div></div>;
}
