/** Shared household medicine inventory: SQLite metadata, private image bytes on disk. */
const crypto = require('crypto');
const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const { Transform } = require('stream');
const { pipeline } = require('stream/promises');
const { prisma } = require('./db');
const { MEDICINE_UPLOAD_DIR, MEDICINE_MAX_UPLOAD_BYTES } = require('./config');

const TEXT_LIMITS = { name: 120, genericName: 120, brand: 120, category: 60, dosageForm: 60, specification: 120, manufacturer: 160, origin: 120, approvalNumber: 100, purpose: 1000, precautions: 1000, notes: 2000, batchNumber: 100, unit: 30, storageLocation: 120, recipient: 80, reason: 200, note: 1000 };
class MedicineError extends Error { constructor(message, statusCode = 400) { super(message); this.name = 'MedicineError'; this.statusCode = statusCode; } }

function cleanText(value, key, { required = false } = {}) {
  if (value == null) { if (required) throw new MedicineError(`请填写${key}。`); return null; }
  if (typeof value !== 'string') throw new MedicineError(`${key}格式无效。`);
  const text = value.trim();
  if (required && !text) throw new MedicineError(`请填写${key}。`);
  if (!text) return null;
  const limit = TEXT_LIMITS[key] || 200;
  if (text.length > limit) throw new MedicineError(`${key}不能超过 ${limit} 个字符。`);
  return text;
}
function cleanNumber(value, label, { positive = false } = {}) { const number = Number(value); if (!Number.isFinite(number) || (positive && number <= 0)) throw new MedicineError(`${label}必须是${positive ? '大于 0 的' : '有效'}数字。`); return number; }
function cleanDate(value, label, { required = false } = {}) { if (value == null || value === '') { if (required) throw new MedicineError(`请填写${label}。`); return null; } if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new MedicineError(`${label}格式应为 YYYY-MM-DD。`); const date = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(date.getTime())) throw new MedicineError(`${label}无效。`); return date; }
function dateValue(date) { return date ? date.toISOString().slice(0, 10) : null; }
async function resolveUserId(user) { if (typeof user?.id === 'string' && user.id) return user.id; const record = await prisma.user.findUnique({ where: { username: user?.username || '' }, select: { id: true } }); if (!record) throw new MedicineError('当前登录账户无效。', 401); return record.id; }
function photoDto(photo) { return { id: photo.id, originalName: photo.originalName, mimeType: photo.mimeType, byteSize: photo.byteSize, createdAt: photo.createdAt.toISOString(), url: `/api/medicine/photos/${photo.id}` }; }
function batchDto(batch) { return { id: batch.id, batchNumber: batch.batchNumber, productionDate: dateValue(batch.productionDate), expiryDate: dateValue(batch.expiryDate), initialQuantity: batch.initialQuantity, remainingQuantity: batch.remainingQuantity, unit: batch.unit, storageLocation: batch.storageLocation, receivedAt: dateValue(batch.receivedAt), createdAt: batch.createdAt.toISOString(), updatedAt: batch.updatedAt.toISOString() }; }
function productDto(product, detailed = false) { const batches = (product.batches || []).map(batchDto); const totalRemaining = batches.reduce((sum, batch) => sum + batch.remainingQuantity, 0); const result = { id: product.id, name: product.name, genericName: product.genericName, brand: product.brand, category: product.category, dosageForm: product.dosageForm, specification: product.specification, manufacturer: product.manufacturer, origin: product.origin, approvalNumber: product.approvalNumber, purpose: product.purpose, precautions: product.precautions, notes: product.notes, creator: product.creator ? product.creator.username : undefined, createdAt: product.createdAt.toISOString(), updatedAt: product.updatedAt.toISOString(), photos: (product.photos || []).map(photoDto), batches, totalRemaining, batchCount: batches.length, nearestExpiryDate: batches.filter((batch) => batch.expiryDate && batch.remainingQuantity > 0).sort((a,b) => a.expiryDate.localeCompare(b.expiryDate))[0]?.expiryDate || null };
  if (detailed) result.useLogs = (product.batches || []).flatMap((batch) => (batch.useLogs || []).map((log) => ({ id: log.id, batchId: batch.id, batchNumber: batch.batchNumber, unit: batch.unit, usedQuantity: log.usedQuantity, usedAt: log.usedAt.toISOString(), recipient: log.recipient, reason: log.reason, note: log.note, operator: log.operator.username }))).sort((a,b) => b.usedAt.localeCompare(a.usedAt));
  return result;
}
const includeProduct = { creator: { select: { username: true } }, photos: { orderBy: { createdAt: 'asc' } }, batches: { orderBy: [{ expiryDate: 'asc' }, { createdAt: 'asc' }] } };
const includeProductDetail = { ...includeProduct, batches: { orderBy: [{ expiryDate: 'asc' }, { createdAt: 'asc' }], include: { useLogs: { include: { operator: { select: { username: true } } }, orderBy: { usedAt: 'desc' }, take: 50 } } } };
function productInput(input) { if (!input || typeof input !== 'object' || Array.isArray(input)) throw new MedicineError('请求体无效。'); return { name: cleanText(input.name, 'name', { required: true }), genericName: cleanText(input.genericName, 'genericName'), brand: cleanText(input.brand, 'brand'), category: cleanText(input.category, 'category', { required: true }), dosageForm: cleanText(input.dosageForm, 'dosageForm'), specification: cleanText(input.specification, 'specification'), manufacturer: cleanText(input.manufacturer, 'manufacturer'), origin: cleanText(input.origin, 'origin'), approvalNumber: cleanText(input.approvalNumber, 'approvalNumber'), purpose: cleanText(input.purpose, 'purpose'), precautions: cleanText(input.precautions, 'precautions'), notes: cleanText(input.notes, 'notes') }; }
function batchInput(input) { if (!input || typeof input !== 'object' || Array.isArray(input)) throw new MedicineError('请求体无效。'); const productionDate = cleanDate(input.productionDate, '生产日期'); const expiryDate = cleanDate(input.expiryDate, '有效期'); if (productionDate && expiryDate && productionDate > expiryDate) throw new MedicineError('有效期不能早于生产日期。'); return { batchNumber: cleanText(input.batchNumber, 'batchNumber'), productionDate, expiryDate, initialQuantity: cleanNumber(input.initialQuantity, '初始数量', { positive: true }), remainingQuantity: input.remainingQuantity == null ? undefined : cleanNumber(input.remainingQuantity, '剩余数量'), unit: cleanText(input.unit, 'unit', { required: true }), storageLocation: cleanText(input.storageLocation, 'storageLocation'), receivedAt: cleanDate(input.receivedAt, '入库日期') || new Date() }; }
async function listProducts(query = {}) { const q = typeof query.q === 'string' ? query.q.trim().slice(0, 100) : ''; const where = { ...(q ? { OR: [{ name: { contains: q } }, { genericName: { contains: q } }, { brand: { contains: q } }, { category: { contains: q } }] } : {}), ...(typeof query.category === 'string' && query.category.trim() ? { category: query.category.trim().slice(0, 60) } : {}) }; const products = await prisma.medicineProduct.findMany({ where, include: includeProduct, orderBy: { updatedAt: 'desc' } }); const items = products.map((product) => productDto(product)); const now = new Date(); const soon = new Date(now); soon.setDate(soon.getDate() + Math.min(Math.max(Number(query.days) || 30, 1), 365)); const filter = query.filter; const filtered = filter === 'low-stock' ? items.filter((item) => item.totalRemaining <= 0 || item.batches.some((batch) => batch.remainingQuantity > 0 && batch.remainingQuantity <= 5)) : filter === 'expiring' ? items.filter((item) => item.nearestExpiryDate && new Date(`${item.nearestExpiryDate}T00:00:00Z`) <= soon) : filter === 'expired' ? items.filter((item) => item.nearestExpiryDate && new Date(`${item.nearestExpiryDate}T00:00:00Z`) < now) : items; return { products: filtered, stats: { productCount: items.length, batchCount: items.reduce((sum, item) => sum + item.batchCount, 0), lowStockCount: items.filter((item) => item.totalRemaining <= 0 || item.batches.some((batch) => batch.remainingQuantity > 0 && batch.remainingQuantity <= 5)).length, expiringCount: items.filter((item) => item.nearestExpiryDate && new Date(`${item.nearestExpiryDate}T00:00:00Z`) >= now && new Date(`${item.nearestExpiryDate}T00:00:00Z`) <= soon).length } }; }
async function getProduct(id) { if (typeof id !== 'string' || id.length > 64) throw new MedicineError('药品标识无效。'); const product = await prisma.medicineProduct.findUnique({ where: { id }, include: includeProductDetail }); if (!product) throw new MedicineError('药品不存在或已删除。', 404); return productDto(product, true); }
async function createProduct(user, input) { return productDto(await prisma.medicineProduct.create({ data: { ...productInput(input), creatorId: await resolveUserId(user) }, include: includeProduct })); }
async function updateProduct(id, input) { await getProduct(id); return productDto(await prisma.medicineProduct.update({ where: { id }, data: productInput(input), include: includeProduct })); }
async function deleteProduct(id) { const product = await prisma.medicineProduct.findUnique({ where: { id }, include: { photos: true } }); if (!product) throw new MedicineError('药品不存在或已删除。', 404); await prisma.medicineProduct.delete({ where: { id } }); await Promise.all(product.photos.map((photo) => unlinkQuietly(photoPath(photo.storedName)))); return { id }; }
async function createBatch(productId, input) { await getProduct(productId); const data = batchInput(input); const remainingQuantity = data.remainingQuantity === undefined ? data.initialQuantity : data.remainingQuantity; if (remainingQuantity < 0 || remainingQuantity > data.initialQuantity) throw new MedicineError('剩余数量必须在 0 到初始数量之间。'); delete data.remainingQuantity; return batchDto(await prisma.medicineBatch.create({ data: { ...data, remainingQuantity, productId } })); }
async function updateBatch(id, input) { const current = await prisma.medicineBatch.findUnique({ where: { id }, include: { _count: { select: { useLogs: true } } } }); if (!current) throw new MedicineError('批次不存在或已删除。', 404); const data = batchInput(input); const remainingQuantity = data.remainingQuantity === undefined ? current.remainingQuantity : data.remainingQuantity; if (remainingQuantity < 0 || data.initialQuantity < remainingQuantity) throw new MedicineError('剩余数量必须在 0 到初始数量之间。'); if (current._count.useLogs && data.initialQuantity < current.initialQuantity - current.remainingQuantity + remainingQuantity) throw new MedicineError('初始数量不能低于已用数量。'); delete data.remainingQuantity; return batchDto(await prisma.medicineBatch.update({ where: { id }, data: { ...data, remainingQuantity } })); }
async function deleteBatch(id) { const batch = await prisma.medicineBatch.findUnique({ where: { id }, include: { _count: { select: { useLogs: true } } } }); if (!batch) throw new MedicineError('批次不存在或已删除。', 404); if (batch._count.useLogs) throw new MedicineError('该批次已有用药流水，不能删除。'); await prisma.medicineBatch.delete({ where: { id } }); return { id }; }
async function recordUse(user, batchId, input) { const operatorId = await resolveUserId(user); if (!input || typeof input !== 'object') throw new MedicineError('请求体无效。'); const usedQuantity = cleanNumber(input.usedQuantity, '用药数量', { positive: true }); const usedAt = input.usedAt ? new Date(input.usedAt) : new Date(); if (Number.isNaN(usedAt.getTime())) throw new MedicineError('用药时间无效。'); return prisma.$transaction(async (tx) => { const batch = await tx.medicineBatch.findUnique({ where: { id: batchId } }); if (!batch) throw new MedicineError('批次不存在或已删除。', 404); if (batch.remainingQuantity < usedQuantity) throw new MedicineError(`库存不足，当前仅剩 ${batch.remainingQuantity} ${batch.unit}。`, 409); const log = await tx.medicineUseLog.create({ data: { batchId, operatorId, usedQuantity, usedAt, recipient: cleanText(input.recipient, 'recipient'), reason: cleanText(input.reason, 'reason'), note: cleanText(input.note, 'note') }, include: { operator: { select: { username: true } }, batch: { select: { batchNumber: true, unit: true } } } }); await tx.medicineBatch.update({ where: { id: batchId }, data: { remainingQuantity: { decrement: usedQuantity } } }); return { id: log.id, batchId, batchNumber: log.batch.batchNumber, unit: log.batch.unit, usedQuantity: log.usedQuantity, usedAt: log.usedAt.toISOString(), recipient: log.recipient, reason: log.reason, note: log.note, operator: log.operator.username }; }); }
function photoPath(storedName) { return path.join(MEDICINE_UPLOAD_DIR, storedName); }
async function unlinkQuietly(file) { try { await fsp.unlink(file); } catch (error) { if (error.code !== 'ENOENT') console.error('药箱图片清理失败:', error); } }
function cleanFilename(value) { const valueString = typeof value === 'string' ? value : ''; const name = valueString.replace(/[\\/\0<>:"|?*\x00-\x1f]/g, '_').replace(/\s+/g, ' ').trim(); return (name || 'medicine-image').slice(0, 180); }
function cleanImageMime(value) { const mime = typeof value === 'string' ? value.split(';')[0].trim().toLowerCase() : ''; if (!['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif'].includes(mime)) throw new MedicineError('仅支持 JPEG、PNG、GIF、WebP 或 AVIF 图片。'); return mime; }
async function uploadPhoto(req, productId) { await getProduct(productId); const declaredSize = Number(req.headers['content-length']); if (Number.isFinite(declaredSize) && (declaredSize < 1 || declaredSize > MEDICINE_MAX_UPLOAD_BYTES)) throw new MedicineError(`图片大小必须在 1 B 到 ${MEDICINE_MAX_UPLOAD_BYTES} B 之间。`, 413); const originalName = cleanFilename(req.headers['x-medicine-file-name']); const mimeType = cleanImageMime(req.headers['content-type']); await fsp.mkdir(MEDICINE_UPLOAD_DIR, { recursive: true }); const storedName = crypto.randomUUID(); const temporary = photoPath(`${storedName}.uploading`); const finalPath = photoPath(storedName); let byteSize = 0; const limiter = new Transform({ transform(chunk, _encoding, callback) { byteSize += chunk.length; if (byteSize > MEDICINE_MAX_UPLOAD_BYTES) return callback(new MedicineError(`单张图片不能超过 ${MEDICINE_MAX_UPLOAD_BYTES} B。`, 413)); callback(null, chunk); } }); try { await pipeline(req, limiter, fs.createWriteStream(temporary, { flags: 'wx' })); if (!byteSize) throw new MedicineError('不能上传空图片。'); await fsp.rename(temporary, finalPath); const photo = await prisma.medicinePhoto.create({ data: { productId, storedName, originalName, mimeType, byteSize } }); return photoDto(photo); } catch (error) { await Promise.all([unlinkQuietly(temporary), unlinkQuietly(finalPath)]); if (error instanceof MedicineError) throw error; if (error?.code === 'ERR_STREAM_PREMATURE_CLOSE') throw new MedicineError('上传被中断。', 400); throw error; } }
async function getPhoto(id) { if (typeof id !== 'string' || id.length > 64) throw new MedicineError('图片标识无效。'); const photo = await prisma.medicinePhoto.findUnique({ where: { id } }); if (!photo) throw new MedicineError('图片不存在或已删除。', 404); return { photo, filePath: photoPath(photo.storedName) }; }
async function deletePhoto(id) { const photo = await prisma.medicinePhoto.findUnique({ where: { id } }); if (!photo) throw new MedicineError('图片不存在或已删除。', 404); await prisma.medicinePhoto.delete({ where: { id } }); await unlinkQuietly(photoPath(photo.storedName)); return { id }; }
module.exports = { MedicineError, MEDICINE_MAX_UPLOAD_BYTES, listProducts, getProduct, createProduct, updateProduct, deleteProduct, createBatch, updateBatch, deleteBatch, recordUse, uploadPhoto, getPhoto, deletePhoto };
