/** Shared initiative scene media library: SQLite metadata + private disk bytes. */
const crypto = require('crypto');
const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const { Transform } = require('stream');
const { pipeline } = require('stream/promises');
const { prisma } = require('./db');
const { INITIATIVE_SCENE_UPLOAD_DIR, INITIATIVE_SCENE_IMAGE_MAX_UPLOAD_BYTES, INITIATIVE_SCENE_AUDIO_MAX_UPLOAD_BYTES, INITIATIVE_SCENE_VIDEO_MAX_UPLOAD_BYTES } = require('./config');
class SceneMediaError extends Error { constructor(message, statusCode = 400) { super(message); this.name = 'SceneMediaError'; this.statusCode = statusCode; } }
const MIMES = { image: new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif']), audio: new Set(['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/webm', 'audio/aac', 'audio/mp4']), video: new Set(['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime']) };
function kindForMime(value) { const mime = typeof value === 'string' ? value.split(';')[0].trim().toLowerCase() : ''; for (const [kind, mimes] of Object.entries(MIMES)) if (mimes.has(mime)) return { kind, mime }; throw new SceneMediaError('只支持 JPEG、PNG、GIF、WebP、AVIF 图片；MP3、WAV、OGG、WebM、AAC 音频；MP4、WebM、OGG、MOV 视频。'); }
function maxForKind(kind) { return kind === 'image' ? INITIATIVE_SCENE_IMAGE_MAX_UPLOAD_BYTES : kind === 'audio' ? INITIATIVE_SCENE_AUDIO_MAX_UPLOAD_BYTES : INITIATIVE_SCENE_VIDEO_MAX_UPLOAD_BYTES; }
function cleanFilename(value) { let name = typeof value === 'string' ? value : ''; try { name = decodeURIComponent(name); } catch {} name = name.replace(/[\\/\0<>:"|?*\x00-\x1f]/g, '_').replace(/\s+/g, ' ').trim(); return (name || 'scene-media').slice(0, 180); }
async function userId(user) { if (typeof user?.id === 'string' && user.id) return user.id; const result = await prisma.user.findUnique({ where: { username: user?.username || '' }, select: { id: true } }); if (!result) throw new SceneMediaError('当前登录账户无效。', 401); return result.id; }
function filePath(storedName) { return path.join(INITIATIVE_SCENE_UPLOAD_DIR, storedName); }
async function unlinkQuietly(value) { try { await fsp.unlink(value); } catch (error) { if (error?.code !== 'ENOENT') console.error('场景媒体清理失败:', error); } }
function dto(media) { return { id: media.id, originalName: media.originalName, mimeType: media.mimeType, kind: media.kind, byteSize: media.byteSize, createdAt: media.createdAt.toISOString(), uploader: media.uploader?.username, url: `/api/initiative/scenes/files/${media.id}` }; }
async function list() { const media = await prisma.dndSceneMedia.findMany({ include: { uploader: { select: { username: true } } }, orderBy: { createdAt: 'desc' } }); return { media: media.map(dto), limits: { image: INITIATIVE_SCENE_IMAGE_MAX_UPLOAD_BYTES, audio: INITIATIVE_SCENE_AUDIO_MAX_UPLOAD_BYTES, video: INITIATIVE_SCENE_VIDEO_MAX_UPLOAD_BYTES } }; }
async function upload(req, user) { const { kind, mime } = kindForMime(req.headers['content-type']); const maxBytes = maxForKind(kind); const declared = Number(req.headers['content-length']); if (Number.isFinite(declared) && (declared < 1 || declared > maxBytes)) throw new SceneMediaError(`该${kind === 'image' ? '图片' : kind === 'audio' ? '音频' : '视频'}最大为 ${Math.round(maxBytes / 1024 / 1024)} MiB。`, 413); await fsp.mkdir(INITIATIVE_SCENE_UPLOAD_DIR, { recursive: true }); const storedName = crypto.randomUUID(); const temporary = filePath(`${storedName}.uploading`); const finalPath = filePath(storedName); let byteSize = 0; const limiter = new Transform({ transform(chunk, _encoding, callback) { byteSize += chunk.length; if (byteSize > maxBytes) return callback(new SceneMediaError(`文件超过 ${Math.round(maxBytes / 1024 / 1024)} MiB 限制。`, 413)); callback(null, chunk); } }); try { await pipeline(req, limiter, fs.createWriteStream(temporary, { flags: 'wx' })); if (!byteSize) throw new SceneMediaError('不能上传空文件。'); await fsp.rename(temporary, finalPath); const media = await prisma.dndSceneMedia.create({ data: { uploaderId: await userId(user), storedName, originalName: cleanFilename(req.headers['x-scene-file-name']), mimeType: mime, kind, byteSize }, include: { uploader: { select: { username: true } } } }); return dto(media); } catch (error) { await Promise.all([unlinkQuietly(temporary), unlinkQuietly(finalPath)]); if (error instanceof SceneMediaError) throw error; if (error?.code === 'ERR_STREAM_PREMATURE_CLOSE') throw new SceneMediaError('上传被中断。', 400); throw error; } }
async function get(id) { if (typeof id !== 'string' || id.length > 64) throw new SceneMediaError('媒体标识无效。'); const media = await prisma.dndSceneMedia.findUnique({ where: { id } }); if (!media) throw new SceneMediaError('媒体不存在或已删除。', 404); return { media, filePath: filePath(media.storedName) }; }
async function remove(id) { const resource = await get(id); await prisma.dndSceneMedia.delete({ where: { id } }); await unlinkQuietly(resource.filePath); return { id }; }
module.exports = { SceneMediaError, list, upload, get, remove };
