'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import ToolHeader from '@/components/common/ToolHeader'; import SearchPanel,{EMPTY_SEARCH_STATE,SearchPanelState} from '@/components/edh/SearchPanel'; import CardTile from '@/components/edh/CardTile'; import CardDetailModal from '@/components/edh/CardDetailModal'; import DeckBoard from '@/components/edh/DeckBoard'; import DeckSidebar from '@/components/edh/DeckSidebar'; import * as api from '@/lib/edh/api'; import { DeckViewMode,EdhCard,EdhDeck,EdhDeckLayout,EdhSearchFilters } from '@/lib/edh/types';
const baseLayout:EdhDeckLayout={viewMode:'free',positions:{}};
function filters(s:SearchPanelState):EdhSearchFilters{return{q:s.q,searchField:s.searchField,colors:s.colors,colorMode:s.colorMode,types:s.types,rarities:s.rarities,cmcMin:s.cmcMin,cmcMax:s.cmcMax >= 16 ? null : s.cmcMax,powerMin:s.powerMin===''?null:Number(s.powerMin),powerMax:s.powerMax===''?null:Number(s.powerMax),toughnessMin:s.toughnessMin===''?null:Number(s.toughnessMin),toughnessMax:s.toughnessMax===''?null:Number(s.toughnessMax),format:s.format,nonReprint:s.nonReprint,commanderOnly:s.commanderOnly};}
export default function EdhBuilderPage(){const[ready,setReady]=useState(false),[state,setState]=useState(EMPTY_SEARCH_STATE),[searched,setSearched]=useState(false),[results,setResults]=useState<EdhCard[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[decks,setDecks]=useState<EdhDeck[]>([]),[activeId,setActiveId]=useState<string|null>(null),[cache,setCache]=useState<Map<string,EdhCard>>(new Map()),[detail,setDetail]=useState<EdhCard|null>(null);
useEffect(()=>{Promise.all([api.listDecks(),api.getCardsMeta()]).then(([ds])=>{setDecks(ds);setActiveId(ds[0]?.id||null);setReady(true)}).catch(e=>setError(e.message))},[]); const active=useMemo(()=>decks.find(d=>d.id===activeId)||null,[decks,activeId]);
useEffect(()=>{if(!active)return;const ids=[...active.cards.map(c=>c.oracleId),...(active.commanderOracleId?[active.commanderOracleId]:[])].filter(i=>!cache.has(i));if(ids.length)api.lookupCards(ids).then(cs=>setCache(p=>{const n=new Map(p);cs.forEach(c=>n.set(c.oracleId,c));return n}))},[active,cache]);
const save=useCallback((id:string,patch:Partial<EdhDeck>)=>api.updateDeck(id,patch).then(d=>setDecks(p=>p.map(x=>x.id===id?d:x))).catch(e=>setError(e.message)),[]); const cardOf=useCallback((id:string)=>cache.get(id),[cache]);
const search=()=>{setSearched(true);setError('');api.searchCards(filters(state)).then(r=>{setResults(r.cards);setTotal(r.total);setCache(p=>{const n=new Map(p);r.cards.forEach(c=>n.set(c.oracleId,c));return n})}).catch(e=>setError(e.message))};
const add=(card:EdhCard,point?:{x:number;y:number})=>{if(!active)return setError('请先新建一个牌组');if(active.commanderOracleId===card.oracleId)return;const ex=active.cards.find(x=>x.oracleId===card.oracleId);if(ex&&!card.typeLine.toLowerCase().includes('basic land'))return;const cards=ex?active.cards.map(x=>x.oracleId===card.oracleId?{...x,quantity:x.quantity+1}:x):[...active.cards,{oracleId:card.oracleId,quantity:1}];const layout={...(active.layout||baseLayout),positions:{...(active.layout?.positions||{}),...(point?{[card.oracleId]:point}:{})}};save(active.id,{cards,layout})};
const commander=(card:EdhCard)=>{if(!active)return;if(!card.isCommanderEligible)return setError('这张牌不能担任指挥官');save(active.id,{commanderOracleId:card.oracleId,cards:active.cards.filter(x=>x.oracleId!==card.oracleId)})};
const layout=(patch:Partial<EdhDeckLayout>)=>active&&save(active.id,{layout:{...(active.layout||baseLayout),...patch}}); const remove=(card:EdhCard)=>active&&save(active.id,{cards:active.cards.map(x=>x.oracleId===card.oracleId?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0)});
if(!ready)return <div className="grid min-h-screen place-items-center bg-[#070915] text-slate-400">载入指挥官工作台…</div>;return <div className="min-h-screen bg-[#070915] text-slate-100"><ToolHeader className="!border-white/10 !bg-[#080a18]/70" textClassName="!text-slate-400 hover:!text-white"/><main className="mx-auto max-w-[1700px] p-4 sm:p-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs tracking-[.18em] text-cyan-300">EDH DECK FORGE</p><h1 className="text-2xl font-semibold">指挥官组卡台</h1></div><div className="flex rounded-xl border border-white/10 bg-white/[.03] p-1">{(['free','type','cmc'] as DeckViewMode[]).map(v=><button key={v} onClick={()=>layout({viewMode:v})} className={`rounded-lg px-3 py-2 text-xs ${active?.layout?.viewMode===v||(v==='free'&&!active?.layout)?'bg-cyan-300 text-slate-950':'text-slate-400'}`}>{v==='free'?'自由桌面':v==='type'?'按类别归拢':'按法力值归拢'}</button>)}</div></header>{error&&<p className="mb-3 rounded-xl bg-rose-500/15 p-3 text-sm text-rose-200">{error}</p>}<div className="grid gap-4 xl:grid-cols-[430px_1fr_220px]"><aside><SearchPanel state={state} onChange={setState} onSearch={search}/><section className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-3"><div className="flex justify-between text-xs text-slate-500"><span>卡池结果</span>{searched&&<span>{total} 张</span>}</div>{!searched?<p className="grid min-h-64 place-items-center text-center text-sm text-slate-500">输入条件后点击搜索<br/>卡池不会自动展示热门牌</p>:<div className="mt-3 grid max-h-[420px] grid-cols-3 gap-2 overflow-auto sm:max-h-[680px]">{results.map(c=><CardTile key={c.oracleId} card={c} onDetails={setDetail} onAdd={add}/>)}</div>}</section></aside><section className="min-h-[520px] rounded-2xl border border-white/10 bg-white/[.02] p-4 sm:min-h-[760px]">{active?<DeckBoard entries={active.cards} commanderOracleId={active.commanderOracleId} cardOf={cardOf} layout={active.layout||baseLayout} onDropCard={(id,p)=>{const c=cardOf(id);if(c)add(c,p)}} onMoveCard={(id,p)=>layout({positions:{...(active.layout?.positions||{}),[id]:p}})} onRemoveOne={remove} onSetCommander={commander} onClearCommander={()=>save(active.id,{commanderOracleId:null})} onDetails={setDetail}/>:<p className="grid h-full place-items-center text-slate-500">先在右侧新建一个牌组</p>}</section><DeckSidebar decks={decks} activeDeckId={activeId} onSelect={setActiveId} onCreate={n=>api.createDeck(n).then(d=>{setDecks(p=>[...p,d]);setActiveId(d.id)})} onDelete={id=>api.deleteDeck(id).then(()=>{setDecks(p=>p.filter(d=>d.id!==id));setActiveId(null)})} onRename={(id,n)=>save(id,{name:n})}/></div></main><CardDetailModal card={detail} onClose={()=>setDetail(null)} onAdd={add} onCommander={commander}/></div>}
